# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 945990dfcd500a9d8cb1ea15c3cbf0d8350dd459286fa889efc7022bbf6113f107887dc0c617ab006dd601c8506d4768ff3afcbc4f8b19745ab773805580ca05

test:
  secret_key_base: 95cfdc39e92266d16dc3a289cddead2df8d12feba8a634d4e1fbb78789cc221fbc8fdd93abba0779b4d3f8b15fc4e46e09878640c195e720225dcc1b8de66f80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
